classroom/urls.py
from django.urls import include, path

from .views import classroom, students, teachers

urlpatterns = [
    path('', classroom.home, name='home'),

    path('contact', classroom.contact, name='contact'),

    path('payment-done/', students.payment_done, name='payment_done'),
    path('payment-canceled/', students.payment_canceled, name='payment_canceled'),
    path('students/', include(([
        path('', students.TutorListView.as_view(), name='tutor_list'),
        path('process-payment/<int:pk>/', students.process_payment, name='process_payment'),
        path('taken/', students.LessonListView.as_view(), name='lesson_list'),
        path('interests/', students.StudentInterestsView.as_view(), name='student_interests'),
        path('grade_level/', students.StudentGradesView.as_view(), name='student_grade_level'),
        path('availability/', students.StudentAvailabilityView.as_view(), name='student_availability'),
        path('sessions/', students.StudentSessionsView.as_view(), name='student_sessions'),
        path('school/', students.StudentSchoolView.as_view(), name='student_school'),
    
    ], 'classroom'), namespace='students')),

    path('teachers/', include(([
        path('', teachers.TutorListView.as_view(), name='lesson_change_list'),
        path('interests/', teachers.TeacherInterestsView.as_view(), name='teacher_interests'),
        path('grade_level/', teachers.TeacherGradesView.as_view(), name='teacher_grade_level'),
        path('availability/', teachers.TeacherAvailabilityView.as_view(), name='teacher_availability'),
        path('sessions/', teachers.TeacherSessionsView.as_view(), name='teacher_sessions'),
        path('school/', teachers.TeacherSchoolView.as_view(), name='teacher_school'),
        path('distance/', teachers.TeacherDistanceView.as_view(), name='teacher_distance'),
        path('rate/', teachers.TeacherRateView.as_view(), name='teacher_rate'),

        path('lesson/add/', teachers.LessonCreateView.as_view(), name='lesson_add'),
        path('lesson/<int:pk>/', teachers.LessonUpdateView.as_view(), name='lesson_change'),
        path('lesson/<int:pk>/delete/', teachers.LessonDeleteView.as_view(), name='lesson_delete'),
        path('lesson/<int:pk>/results/', teachers.LessonResultsView.as_view(), name='lesson_results'),

    ], 'classroom'), namespace='teachers')),
]

tru/urls.py
from django.urls import include, path
from django.contrib import admin
from classroom.views import classroom, students, teachers
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('classroom.urls')),
    path('paypal/', include('paypal.standard.ipn.urls')),

    path('about/', classroom.AboutView.as_view(), name='about'),

    path('services/', classroom.ServicesView.as_view(), name='services'),
    path('faq/', classroom.FAQView.as_view(), name='faq'),
    path('pricing/', classroom.PricingView.as_view(), name='pricing'),

    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', classroom.SignUpView.as_view(), name='signup'),
    path('accounts/terms/', classroom.TermsView.as_view(), name='terms'),
    path('accounts/privacy/', classroom.PrivacyView.as_view(), name='privacy'),
    path('accounts/signup/student/', students.StudentSignUpView.as_view(), name='student_signup'),
    path('accounts/signup/teacher/', teachers.TeacherSignUpView.as_view(), name='teacher_signup'),
]

urlpatterns += staticfiles_urlpatterns()

trututoring/classroom/urls.py
from django.urls import include, path
from django.contrib import admin
from .views import classroom, students, teachers

urlpatterns = [
    path('', classroom.home, name='home'), 

    path('students/', include(([
        path('', students.QuizListView.as_view(), name='quiz_list'),
        path('topics/', students.StudentTopicsView.as_view(), name='student_topics'),
    ], 'classroom'), namespace='students')),
    
    
    path('teachers/', include(([
        path('values', teachers.TeacherValuesView.as_view(), name='values'),
    ], 'classroom'), namespace='teachers')),
]

trututoring/classroom/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.html import escape, mark_safe


class User(AbstractUser):
    is_student = models.BooleanField(default=False)
    is_teacher = models.BooleanField(default=False)


class Subject(models.Model):
    name = models.CharField(max_length=30)
    color = models.CharField(max_length=7, default='#007bff')

    def __str__(self):
        return self.name

    def get_html_badge(self):
        name = escape(self.name)
        color = escape(self.color)
        html = '<span class="badge badge-primary" style="background-color: %s">%s</span>' % (color, name)
        return mark_safe(html)


class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    topics = models.ManyToManyField(Subject, related_name='topical_students')

    def __str__(self):
        return self.user.username

classroom/views/classroom.py
from django.shortcuts import redirect, render
from django.views.generic import TemplateView
from django.views.generic.list import ListView
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from ..forms import ContactForm
from ..models import Lesson

#class AboutView(TemplateView):
#    template_name = 'classroom/about.html'

class SignUpView(TemplateView):
    template_name = 'registration/signup.html'

class TermsView(TemplateView):
    template_name = 'registration/terms.html'

class PrivacyView(TemplateView):
    template_name = 'registration/privacy.html'    

class ServicesView(TemplateView):
    template_name = 'classroom/services.html'

class FAQView(TemplateView):
    template_name = 'classroom/faq.html'

class PricingView(TemplateView):
    template_name = 'classroom/pricing.html'



def home(request):
    if request.user.is_authenticated:
        if request.user.is_teacher:
            #return render(request, 'classroom/teachers/lesson_change_list.html')
            return redirect('teachers:lesson_change_list')
        else:
            #return render(request, 'classroom/students/tutor_list.html')
            return redirect('students:tutor_list')
    return render(request, 'classroom/home.html')



def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            sender_name = form.cleaned_data['name']
            sender_email = form.cleaned_data['email']

            message = "{0} has sent you a new message:\n\n{1}".format(sender_name, form.cleaned_data['message'])
            send_mail('New Enquiry', message, sender_email, ['trututoring@gmail.com'])
            return render(request, 'classroom/thanks.html')
    else:
        form = ContactForm()

    return render(request, 'classroom/contact.html', {'form': form})


class AboutView(ListView):
    model = Lesson
    template_name = 'classroom/about.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        num = Lesson.objects.count()
        context['count'] = num+556      # 556 completed already at time of release
        return context

classroom/views/students.py
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.db.models import Count
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.csrf import csrf_exempt
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, ListView, UpdateView, TemplateView
from django.conf import settings

from decimal import Decimal
from paypal.standard.forms import PayPalPaymentsForm

from ..decorators import student_required
from ..forms import StudentInterestsForm, StudentSignUpForm, StudentGradesForm, StudentAvailabilityForm, StudentSessionsForm, StudentSchoolForm
from ..models import Student, User, Lesson, Teacher

class StudentSignUpView(CreateView):
    model = User
    form_class = StudentSignUpForm
    template_name = 'registration/signup_form.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'student'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('students:tutor_list')


# Student Profile Fields


@method_decorator([login_required, student_required], name='dispatch')
class StudentInterestsView(UpdateView):
    model = Student
    form_class = StudentInterestsForm
    template_name = 'classroom/students/interests_form.html'
    success_url = reverse_lazy('students:tutor_list')

    def get_object(self):
        return self.request.user.student

    def form_valid(self, form):
        return super().form_valid(form)

@method_decorator([login_required, student_required], name='dispatch')
class StudentGradesView(UpdateView):
    model = Student
    form_class = StudentGradesForm
    template_name = 'classroom/students/grade_level_form.html'
    success_url = reverse_lazy('students:tutor_list')

    def get_object(self):
        return self.request.user.student

    def form_valid(self, form):
        return super().form_valid(form)

@method_decorator([login_required, student_required], name='dispatch')
class StudentAvailabilityView(UpdateView):
    model = Student
    form_class = StudentAvailabilityForm
    template_name = 'classroom/students/availability_form.html'
    success_url = reverse_lazy('students:tutor_list')

    def get_object(self):
        return self.request.user.student

    def form_valid(self, form):
        return super().form_valid(form)

@method_decorator([login_required, student_required], name='dispatch')
class StudentSessionsView(UpdateView):
    model = Student
    form_class = StudentSessionsForm
    template_name = 'classroom/students/sessions_form.html'
    success_url = reverse_lazy('students:tutor_list')

    def get_object(self):
        return self.request.user.student

    def form_valid(self, form):
        return super().form_valid(form)

@method_decorator([login_required, student_required], name='dispatch')
class StudentSchoolView(UpdateView):
    model = Student
    form_class = StudentSchoolForm
    template_name = 'classroom/students/school_form.html'
    success_url = reverse_lazy('students:tutor_list')

    def get_object(self):
        return self.request.user.student

    def form_valid(self, form):
        return super().form_valid(form)



#@method_decorator([login_required, student_required], name='dispatch')
#class StudentTutorListView(TemplateView):
#    template_name = 'classroom/students/tutor_list.html'


@method_decorator([login_required, student_required], name='dispatch')
class TutorListView(ListView):
    model = Student
    ordering = ('name', )
    context_object_name = 'teachers'
    template_name = 'classroom/students/tutor_list.html'

#    def get_queryset(self):
#        student = self.request.user.student
#        student_interests = student.interests.values_list('pk', flat=True)
#        queryset = Lesson.objects.filter(subject__in=student_interests) \
#            .annotate() \
#            .filter()
#        return queryset

    def get_queryset(self):
        student = self.request.user.student
        student_interests = student.interests.values_list('pk', flat=True)
        queryset = Teacher.objects.distinct() \
            .filter(interests__in=student_interests)
        return queryset


@method_decorator([login_required, student_required], name='dispatch')
class LessonListView(ListView):
    model = Lesson
    ordering = ('name', )
    context_object_name = 'lessons'
    template_name = 'classroom/students/lesson_list.html'

    def get_queryset(self):
        student_username = self.request.user.username
        queryset = Lesson.objects.all() \
            .filter(name=student_username)
        return queryset



@login_required
@student_required
def process_payment(request, pk):
    host = request.get_host()
    lesson = get_object_or_404(Lesson, pk=pk)
 
    paypal_dict = {
        'business': settings.PAYPAL_RECEIVER_EMAIL,
        'amount': lesson.rate,
        'item_name': 'TRU Tutor: {}'.format(lesson.tutor.user.email),
        'invoice': str(lesson.id),
        'currency_code': 'USD',
        'notify_url': 'http://{}{}'.format(host, reverse('paypal-ipn')),
        'return_url': 'http://{}{}'.format(host, reverse('payment_done')),
        'cancel_return': 'http://{}{}'.format(host, reverse('payment_canceled')),
    }
 
    form = PayPalPaymentsForm(initial=paypal_dict)
    return render(request, 'classroom/students/process_payment.html', {'form': form})


@csrf_exempt
def payment_done(request):
    #return redirect('students:payment_done')
    #return redirect('students:tutor_list')
    return render(request, 'classroom/students/payment_done.html')
 
 
@csrf_exempt
def payment_canceled(request):
    #return redirect('students:payment_done')
    #return redirect('students:tutor_list')
    return render(request, 'classroom/students/payment_canceled.html')


#stripe.api_key = settings.STRIPE_SECRET_KEY
#
#@login_required
#@student_required
#def charge(request, pk): # new
#    lesson = get_object_or_404(Lesson, pk=pk)
#
#    if request.method == 'POST':
#        charge = stripe.Charge.create(
#            amount=2250,
#            currency='usd',
#            description='TUTOR: ' + lesson.tutor.user.username,
#            source=request.POST['stripeToken'],
#        )
#
#        lesson.paid = True
#        lesson.save()
#
#        #return render(request, 'classroom/students/charge.html')
#        return redirect('students:lesson_list')


    

trututoring/classroom/views/classroom.py
from django.shortcuts import redirect, render
from django.views.generic import TemplateView


class SignUpView(TemplateView):
    template_name = 'registration/signup.html'


def home(request):
    if request.user.is_authenticated:
        if request.user.is_teacher:
            return render(request, 'classroom/teachers/values.html')
        else:
            return render(request, 'classroom/students/quiz_list.html')
    return render(request, 'classroom/home.html')

trututoring/classroom/views/students.py
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.db.models import Count
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, ListView, UpdateView, TemplateView

from ..decorators import student_required
from ..forms import StudentTopicsForm, StudentSignUpForm
from ..models import Student, User


class StudentSignUpView(CreateView):
    model = User
    form_class = StudentSignUpForm
    template_name = 'registration/signup_form.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'student'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
#        return render(request, 'classroom/students/quiz_list.html')
        return redirect('students:quiz_list')

@method_decorator([login_required, student_required], name='dispatch')
class StudentTopicsView(UpdateView):
    model = Student
    form_class = StudentTopicsForm
    template_name = 'classroom/students/topics_form.html'
    success_url = reverse_lazy('students:quiz_list')

    def get_object(self):
        return self.request.user.student

    def form_valid(self, form):
        messages.success(self.request, 'topics updated with success!')
        return super().form_valid(form)


@method_decorator([login_required, student_required], name='dispatch')
class QuizListView(TemplateView):
    template_name = 'classroom/students/quiz_list.html'

trututoring/classroom/views/teachers.py
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.db.models import Avg, Count
from django.forms import inlineformset_factory
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import (CreateView, DeleteView, DetailView, ListView,
                                  UpdateView, TemplateView)

from ..decorators import teacher_required
from ..forms import TeacherSignUpForm
from ..models import Subject, Student, User


class TeacherSignUpView(CreateView):
    model = User
    form_class = TeacherSignUpForm
    template_name = 'registration/signup_form.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'tutor'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        #return render(request, 'classroom/teachers/values.html')
        return redirect('teachers:values')


@method_decorator([login_required, teacher_required], name='dispatch')
class TeacherValuesView(TemplateView):
    template_name = 'classroom/teachers/values.html'

classroom/templates/classroom/teachers/availability_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<div class="login-card ">

  <h2 id="title" class="mb-3">Update Your Availability</h2>
  <form method="post" novalidate>
    {% csrf_token %}
    {{ form }}
    <div class="sign-btn">
      <button type="submit" id="yes-btn">Save changes</button>
      <a href="{% url 'teachers:lesson_change_list' %}" id="hit-btn">Nevermind</a>
    </div> 
  </form>

</div>
{% endblock %}

classroom/templates/classroom/teachers/lesson_change_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
{% load widget_tweaks %}

{% block content %}
  
  <div class="login-card ">

    <h2 id="title" class="mb-3">Update Lesson</h2>
    
    <form method="post" novalidate>
      {% csrf_token %}
      {{ form }}
      <div class="triple-btn">
        <button type="submit" id="yes-btn">Update</button>
        <a href="{% url 'teachers:lesson_delete' lesson.pk %}" id="no-btn">Delete</a>
        <a href="{% url 'teachers:lesson_change_list' %}" id="hit-btn">Close</a>
      </div>
    </form>
  </div>
{% endblock %}

classroom/templates/classroom/teachers/lesson_change_list.html
{% extends 'base.html' %}


{% block content %}
<div class="main-card">
  <div class="row align-items-center my-5">

    <div style="padding:1em;" class="col-lg-5 text-center">
      <h1 class="font-weight-light">Start Teaching!</h1>
      {% if user.teacher.verified %}
        <br>
        <p>Interested students will get it touch with you <i>by email</i> shortly!</p>
        <p>As a verified tutor, your base pay begins at $17.50/hour and you get access to incentive pay structures and bonus opportunities.</p>
        <p>With verification, students are far more likely to contact you about lessons.</p>
        <p>You also get full access to our tutoring resources and company support!</p>
      {% else %}
        <br>
        <p><strong>Important: </strong> Currently, you are not a verified TRU Tutor.</p>
        <p>Without verification, students may be less likely to contact you for lessons.</p>
        <p>As a verified tutor, your base pay begins at $17.50/hour and you get access to incentive pay structures and bonus opportunities.</p>
        <p>You also get full access to our tutoring resources and ongoing support!</p>
        <p>To apply for verification, please email <i>trututoring@gmail.com</i>!</p>
      {% endif %}
    </div>

    <div class="col-lg-7">
      <div class="card h-100">
        <div class="card-body">
          {% include 'classroom/teachers/_header.html' with active='new' %}
          <hr id="prof-line"> 
          <p class="text-muted">
            Subjects:&nbsp;{% for subject in user.teacher.interests.all %} {{ subject.get_html_badge }}{% endfor %}
            <a href="{% url 'teachers:teacher_interests' %}"><small>(update)</small></a>
          </p>
          <p class="text-muted">
              School:&nbsp;<span id="badger">{{ user.teacher.school }}</span>
              <a href="{% url 'teachers:teacher_school' %}"><small>(update)</small></a>
          </p>
          {% if user.teacher.verified %}{% else %}
          <p class="text-muted">
            Asking Rate:&nbsp;<span id="badger">${{ user.teacher.rate }}/hour</span>
            <a href="{% url 'teachers:teacher_rate' %}"><small>(update)</small></a>
          </p>
          {% endif %}
          <p class="text-muted">
            Grade(s):&nbsp;{% for grade in user.teacher.grade_level.all %} {{ grade.get_html_badge }}{% endfor %}
            <a href="{% url 'teachers:teacher_grade_level' %}"><small>(update)</small></a>
          </p>
          <p class="text-muted">
            Availability:&nbsp;{% for availability in user.teacher.availability.all %} {{ availability.get_html_badge }}{% endfor %}
            <a href="{% url 'teachers:teacher_availability' %}"><small>(update)</small></a>
          </p>
          <p class="text-muted">
            Sessions/week:&nbsp;{% for session in user.teacher.sessions.all %} {{ session.get_html_badge }}{% endfor %}
            <a href="{% url 'teachers:teacher_sessions' %}"><small>(update)</small></a>
          </p>
          <p class="text-muted">
            Distance:&nbsp;{% for distance in user.teacher.distance.all %} {{ distance.get_html_badge }}{% endfor %}
            <a href="{% url 'teachers:teacher_distance' %}"><small>(update)</small></a>
          </p>
        </div>
      </div>

    </div>
  </div>
  
  <h6 class="font-weight-normal text-left"><strong>Important: </strong>Below, add all scheduled lessons. Please allow students at least 24 hours to complete payment.</h6>
  <hr id="prof-line"> 
  <div class="card text-black bg-white my-4 py-2 z-depth-1">
    <div class="card-body">
      <h2 id="session-title" class="mb-3">Your Lessons
        <a href="{% url 'teachers:lesson_add' %}" class="text-right" id="add-lesson-btn" role="button">Add a lesson</a>
        <a href="{% url 'teachers:lesson_add' %}" class="text-right" id="add-lesson-plus" role="button"><i class="fas fa-plus"></i></a>
      </h2>
      
      <table id="session-table" class="table mb-0 table-striped">
        <thead>
          <tr>
            <th>Student</th>
            <th>Email</th>
            <th>Date</th>
            <th>Zoom Link + Meeting Details</th>
            <th>Lesson Rate</th>
            <th>Paid?</th>
          </tr>
        </thead>
        <tbody>
          {% for lesson in user.teacher.lessons.all %}
            <tr>
              {% if lesson.paid %}
                <td class="align-middle">{{ lesson.name }}</td>
              {% else %}
                <td class="align-middle"><a id="course-descriptor" href="{% url 'teachers:lesson_change' lesson.pk %}">{{ lesson.name }}</a></td>
              {% endif %}
              <td class="align-middle">
                <a class="material-url" href="mailto:{{lesson.getStudentUser.email}}">{{ lesson.getStudentUser.email }}</a>
              </td>
              <td class="align-middle">{{ lesson.date }}</td>
              <td style="width:50%" class="align-middle">{{ lesson.material }}</td>
              <td class="align-middle">
                
                <script>
                  function CurrencyFormatted(amount) {
                    var i = parseFloat(amount);
                    if(isNaN(i)) { i = 0.00; }
                    var minus = '';
                    if(i < 0) { minus = '-'; }
                    i = Math.abs(i);
                    i = parseInt((i + .005) * 100);
                    i = i / 100;
                    s = new String(i);
                    if(s.indexOf('.') < 0) { s += '.00'; }
                    if(s.indexOf('.') == (s.length - 2)) { s += '0'; }
                    s = minus + s;
                    return s;
                  }
                  var amount = '{{ lesson.rate }}';
                  var html = CurrencyFormatted(amount); 
                  document.write('$' + html + '/hour');
                </script>

              </td>

              <td class="align-middle">{% if lesson.paid %}<span style="font-weight: bold; color:green">Yes</span>{% else %}<span>No</span>{% endif %}</td>
            </tr>
          {% empty %}
            <tr>
              <td class="bg-light text-center font-italic" colspan="6">You haven't completed any lessons yet.</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
      
    </div>
  </div>


</div>
{% endblock %}

classroom/templates/classroom/teachers/lesson_delete_confirm.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<div class="login-card ">

  <h2 id="title" class="mb-3">Confirm Deletion</h2>
  <p class="lead">Are you sure you want to delete this lesson? There is no going back.</p>
  <form method="post" novalidate>
    {% csrf_token %}
    <div class="sign-btn">
      <button type="submit" id="no-btn">Yes, I'm sure</button>
      <a href="{% url 'teachers:lesson_change' lesson.pk %}" id="hit-btn">Nevermind</a>
    </div>
  </form>

</div>
{% endblock %}

classroom/templates/classroom/teachers/quiz_change_list.html
{% extends 'base.html' %}


{% block content %}
<div class="main-card">
  <div class="row align-items-center my-5">

    <div class="col-lg-5 text-center">
      <h1 class="font-weight-light">Start Teaching!</h1>
      {% if user.teacher.verified %}
        <p>Interested students will get it touch with you <i>by email</i> shortly!</p>
        <p>As a verified tutor, your base pay begins at $17.50/hour and you get access to incentive pay structures and bonus opportunities.</p>
        <p>With verification, students are far more likely to contact you about lessons.</p>
        <p>You also get full access to our tutoring resources and ongoing company support!</p>
      {% else %}
        <br>
        <p><strong>Important: </strong> Currently, you are not a verified TRU Tutor.</p>
        <p>Without verification, students may be less likely to contact you about lessons.</p>
        <p>As a verified tutor, your base pay begins at $17.50/hour and you get access to incentive pay structures and bonus opportunities.</p>
        <p>You also get full access to our tutoring resources and ongoing company support!</p>
        <p>To apply, please email <i>trututoring@gmail.com</i>!</p>
      {% endif %}
    </div>

    <div class="col-lg-7">
      <div class="card h-100">
        <div class="card-body">
          {% include 'classroom/teachers/_header.html' with active='new' %}
          <hr id="prof-line"> 
          <p class="text-muted">
            Subjects:&nbsp;{% for subject in user.teacher.interests.all %} {{ subject.get_html_badge }}{% endfor %}
            <a href="{% url 'teachers:teacher_interests' %}"><small>(update)</small></a>
          </p>
          <p class="text-muted">
              School:&nbsp;<span class="badge badge-primary" style="background-color:#505050;">{{ user.teacher.school }}</span>
              <a href="{% url 'teachers:teacher_school' %}"><small>(update)</small></a>
          </p>
          <p class="text-muted">
            Asking Rate:&nbsp;<span class="badge badge-primary" style="background-color:#505050;">${{ user.teacher.rate }}/hour</span>
            <a href="{% url 'teachers:teacher_rate' %}"><small>(update)</small></a>
          </p>
          <p class="text-muted">
            Grade:&nbsp;{% for grade in user.teacher.grade_level.all %} {{ grade.get_html_badge }}{% endfor %}
            <a href="{% url 'teachers:teacher_grade_level' %}"><small>(update)</small></a>
          </p>
          <p class="text-muted">
            Availability:&nbsp;{% for availability in user.teacher.availability.all %} {{ availability.get_html_badge }}{% endfor %}
            <a href="{% url 'teachers:teacher_availability' %}"><small>(update)</small></a>
          </p>
          <p class="text-muted">
            Sessions/week:&nbsp;{% for session in user.teacher.sessions.all %} {{ session.get_html_badge }}{% endfor %}
            <a href="{% url 'teachers:teacher_sessions' %}"><small>(update)</small></a>
          </p>
          <p class="text-muted">
            Distance:&nbsp;{% for distance in user.teacher.distance.all %} {{ distance.get_html_badge }}{% endfor %}
            <a href="{% url 'teachers:teacher_distance' %}"><small>(update)</small></a>
          </p>
        </div>
      </div>

    </div>
  </div>

  <hr id="prof-line"> 
  <!--
  <div class="card text-black bg-white my-4 py-2 z-depth-1">
    <div class="card-body">
      <h2 id="session-title" class="mb-3">My Sessions
        <a href="{% url 'teachers:quiz_add' %}" class="text-right" id="add-quiz-btn" role="button">Add session</a>
      </h2>
      
      <table id="session-table" class="table mb-0 table-striped">
        <thead>
          <tr>
            <th>Name</th>
            <th>Subject</th>
            <th>Zoom Meeting ID</th>
          </tr>
        </thead>
        <tbody>
          {% for quiz in user.quizzes.all %}
            <tr>
              <td class="align-middle"><a id="course-descriptor" href="{% url 'teachers:quiz_change' quiz.pk %}">{{ quiz.name }}</a></td>
              <td class="align-middle">{{ quiz.subject.get_html_badge }}</td>
              <td class="align-middle">{{ quiz.zoom }}</td>
            </tr>
          {% empty %}
            <tr>
              <td class="bg-light text-center font-italic" colspan="5">You haven't created any sessions yet.</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
      
    </div>
  </div>


</div>
{% endblock %}