classroom/urls.py
from django.urls import include, path

from .views import classroom, students, teachers

urlpatterns = [
    path('', classroom.home, name='home'),

    path('contact', classroom.contact, name='contact'),

    path('payment-done/', students.payment_done, name='payment_done'),
    path('payment-canceled/', students.payment_canceled, name='payment_canceled'),
    path('students/', include(([
        path('', students.TutorListView.as_view(), name='tutor_list'),
        path('process-payment/<int:pk>/', students.process_payment, name='process_payment'),
        path('taken/', students.LessonListView.as_view(), name='lesson_list'),
        path('interests/', students.StudentInterestsView.as_view(), name='student_interests'),
        path('grade_level/', students.StudentGradesView.as_view(), name='student_grade_level'),
        path('availability/', students.StudentAvailabilityView.as_view(), name='student_availability'),
        path('sessions/', students.StudentSessionsView.as_view(), name='student_sessions'),
        path('school/', students.StudentSchoolView.as_view(), name='student_school'),
    
    ], 'classroom'), namespace='students')),

    path('teachers/', include(([
        path('', teachers.TutorListView.as_view(), name='lesson_change_list'),
        path('interests/', teachers.TeacherInterestsView.as_view(), name='teacher_interests'),
        path('grade_level/', teachers.TeacherGradesView.as_view(), name='teacher_grade_level'),
        path('availability/', teachers.TeacherAvailabilityView.as_view(), name='teacher_availability'),
        path('sessions/', teachers.TeacherSessionsView.as_view(), name='teacher_sessions'),
        path('school/', teachers.TeacherSchoolView.as_view(), name='teacher_school'),
        path('distance/', teachers.TeacherDistanceView.as_view(), name='teacher_distance'),
        path('rate/', teachers.TeacherRateView.as_view(), name='teacher_rate'),

        path('lesson/add/', teachers.LessonCreateView.as_view(), name='lesson_add'),
        path('lesson/<int:pk>/', teachers.LessonUpdateView.as_view(), name='lesson_change'),
        path('lesson/<int:pk>/delete/', teachers.LessonDeleteView.as_view(), name='lesson_delete'),
        path('lesson/<int:pk>/results/', teachers.LessonResultsView.as_view(), name='lesson_results'),

    ], 'classroom'), namespace='teachers')),
]

tru/urls.py
from django.urls import include, path
from django.contrib import admin
from classroom.views import classroom, students, teachers
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('classroom.urls')),
    path('paypal/', include('paypal.standard.ipn.urls')),

    path('about/', classroom.AboutView.as_view(), name='about'),

    path('services/', classroom.ServicesView.as_view(), name='services'),
    path('faq/', classroom.FAQView.as_view(), name='faq'),
    path('pricing/', classroom.PricingView.as_view(), name='pricing'),

    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', classroom.SignUpView.as_view(), name='signup'),
    path('accounts/terms/', classroom.TermsView.as_view(), name='terms'),
    path('accounts/privacy/', classroom.PrivacyView.as_view(), name='privacy'),
    path('accounts/signup/student/', students.StudentSignUpView.as_view(), name='student_signup'),
    path('accounts/signup/teacher/', teachers.TeacherSignUpView.as_view(), name='teacher_signup'),
]

urlpatterns += staticfiles_urlpatterns()

trututoring/classroom/urls.py
from django.urls import include, path
from django.contrib import admin
from .views import classroom, students, teachers

urlpatterns = [
    path('', classroom.home, name='home'), 

    path('students/', include(([
        path('', students.QuizListView.as_view(), name='quiz_list'),
        path('topics/', students.StudentTopicsView.as_view(), name='student_topics'),
    ], 'classroom'), namespace='students')),
    
    
    path('teachers/', include(([
        path('values', teachers.TeacherValuesView.as_view(), name='values'),
    ], 'classroom'), namespace='teachers')),
]

trututoring/classroom/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.html import escape, mark_safe


class User(AbstractUser):
    is_student = models.BooleanField(default=False)
    is_teacher = models.BooleanField(default=False)


class Subject(models.Model):
    name = models.CharField(max_length=30)
    color = models.CharField(max_length=7, default='#007bff')

    def __str__(self):
        return self.name

    def get_html_badge(self):
        name = escape(self.name)
        color = escape(self.color)
        html = '<span class="badge badge-primary" style="background-color: %s">%s</span>' % (color, name)
        return mark_safe(html)


class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    topics = models.ManyToManyField(Subject, related_name='topical_students')

    def __str__(self):
        return self.user.username

classroom/views/classroom.py
from django.shortcuts import redirect, render
from django.views.generic import TemplateView
from django.views.generic.list import ListView
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from ..forms import ContactForm
from ..models import Lesson

#class AboutView(TemplateView):
#    template_name = 'classroom/about.html'

class SignUpView(TemplateView):
    template_name = 'registration/signup.html'

class TermsView(TemplateView):
    template_name = 'registration/terms.html'

class PrivacyView(TemplateView):
    template_name = 'registration/privacy.html'    

class ServicesView(TemplateView):
    template_name = 'classroom/services.html'

class FAQView(TemplateView):
    template_name = 'classroom/faq.html'

class PricingView(TemplateView):
    template_name = 'classroom/pricing.html'



def home(request):
    if request.user.is_authenticated:
        if request.user.is_teacher:
            #return render(request, 'classroom/teachers/lesson_change_list.html')
            return redirect('teachers:lesson_change_list')
        else:
            #return render(request, 'classroom/students/tutor_list.html')
            return redirect('students:tutor_list')
    return render(request, 'classroom/home.html')



def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            sender_name = form.cleaned_data['name']
            sender_email = form.cleaned_data['email']

            message = "{0} has sent you a new message:\n\n{1}".format(sender_name, form.cleaned_data['message'])
            send_mail('New Enquiry', message, sender_email, ['trututoring@gmail.com'])
            return render(request, 'classroom/thanks.html')
    else:
        form = ContactForm()

    return render(request, 'classroom/contact.html', {'form': form})


class AboutView(ListView):
    model = Lesson
    template_name = 'classroom/about.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        num = Lesson.objects.count()
        context['count'] = num+556      # 556 completed already at time of release
        return context

classroom/views/students.py
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.db.models import Count
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.csrf import csrf_exempt
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, ListView, UpdateView, TemplateView
from django.conf import settings

from decimal import Decimal
from paypal.standard.forms import PayPalPaymentsForm

from ..decorators import student_required
from ..forms import StudentInterestsForm, StudentSignUpForm, StudentGradesForm, StudentAvailabilityForm, StudentSessionsForm, StudentSchoolForm
from ..models import Student, User, Lesson, Teacher

class StudentSignUpView(CreateView):
    model = User
    form_class = StudentSignUpForm
    template_name = 'registration/signup_form.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'student'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('students:tutor_list')


# Student Profile Fields


@method_decorator([login_required, student_required], name='dispatch')
class StudentInterestsView(UpdateView):
    model = Student
    form_class = StudentInterestsForm
    template_name = 'classroom/students/interests_form.html'
    success_url = reverse_lazy('students:tutor_list')

    def get_object(self):
        return self.request.user.student

    def form_valid(self, form):
        return super().form_valid(form)

@method_decorator([login_required, student_required], name='dispatch')
class StudentGradesView(UpdateView):
    model = Student
    form_class = StudentGradesForm
    template_name = 'classroom/students/grade_level_form.html'
    success_url = reverse_lazy('students:tutor_list')

    def get_object(self):
        return self.request.user.student

    def form_valid(self, form):
        return super().form_valid(form)

@method_decorator([login_required, student_required], name='dispatch')
class StudentAvailabilityView(UpdateView):
    model = Student
    form_class = StudentAvailabilityForm
    template_name = 'classroom/students/availability_form.html'
    success_url = reverse_lazy('students:tutor_list')

    def get_object(self):
        return self.request.user.student

    def form_valid(self, form):
        return super().form_valid(form)

@method_decorator([login_required, student_required], name='dispatch')
class StudentSessionsView(UpdateView):
    model = Student
    form_class = StudentSessionsForm
    template_name = 'classroom/students/sessions_form.html'
    success_url = reverse_lazy('students:tutor_list')

    def get_object(self):
        return self.request.user.student

    def form_valid(self, form):
        return super().form_valid(form)

@method_decorator([login_required, student_required], name='dispatch')
class StudentSchoolView(UpdateView):
    model = Student
    form_class = StudentSchoolForm
    template_name = 'classroom/students/school_form.html'
    success_url = reverse_lazy('students:tutor_list')

    def get_object(self):
        return self.request.user.student

    def form_valid(self, form):
        return super().form_valid(form)



#@method_decorator([login_required, student_required], name='dispatch')
#class StudentTutorListView(TemplateView):
#    template_name = 'classroom/students/tutor_list.html'


@method_decorator([login_required, student_required], name='dispatch')
class TutorListView(ListView):
    model = Student
    ordering = ('name', )
    context_object_name = 'teachers'
    template_name = 'classroom/students/tutor_list.html'

#    def get_queryset(self):
#        student = self.request.user.student
#        student_interests = student.interests.values_list('pk', flat=True)
#        queryset = Lesson.objects.filter(subject__in=student_interests) \
#            .annotate() \
#            .filter()
#        return queryset

    def get_queryset(self):
        student = self.request.user.student
        student_interests = student.interests.values_list('pk', flat=True)
        queryset = Teacher.objects.distinct() \
            .filter(interests__in=student_interests)
        return queryset


@method_decorator([login_required, student_required], name='dispatch')
class LessonListView(ListView):
    model = Lesson
    ordering = ('name', )
    context_object_name = 'lessons'
    template_name = 'classroom/students/lesson_list.html'

    def get_queryset(self):
        student_username = self.request.user.username
        queryset = Lesson.objects.all() \
            .filter(name=student_username)
        return queryset



@login_required
@student_required
def process_payment(request, pk):
    host = request.get_host()
    lesson = get_object_or_404(Lesson, pk=pk)
 
    paypal_dict = {
        'business': settings.PAYPAL_RECEIVER_EMAIL,
        'amount': lesson.rate,
        'item_name': 'TRU Tutor: {}'.format(lesson.tutor.user.email),
        'invoice': str(lesson.id),
        'currency_code': 'USD',
        'notify_url': 'http://{}{}'.format(host, reverse('paypal-ipn')),
        'return_url': 'http://{}{}'.format(host, reverse('payment_done')),
        'cancel_return': 'http://{}{}'.format(host, reverse('payment_canceled')),
    }
 
    form = PayPalPaymentsForm(initial=paypal_dict)
    return render(request, 'classroom/students/process_payment.html', {'form': form})


@csrf_exempt
def payment_done(request):
    #return redirect('students:payment_done')
    #return redirect('students:tutor_list')
    return render(request, 'classroom/students/payment_done.html')
 
 
@csrf_exempt
def payment_canceled(request):
    #return redirect('students:payment_done')
    #return redirect('students:tutor_list')
    return render(request, 'classroom/students/payment_canceled.html')


#stripe.api_key = settings.STRIPE_SECRET_KEY
#
#@login_required
#@student_required
#def charge(request, pk): # new
#    lesson = get_object_or_404(Lesson, pk=pk)
#
#    if request.method == 'POST':
#        charge = stripe.Charge.create(
#            amount=2250,
#            currency='usd',
#            description='TUTOR: ' + lesson.tutor.user.username,
#            source=request.POST['stripeToken'],
#        )
#
#        lesson.paid = True
#        lesson.save()
#
#        #return render(request, 'classroom/students/charge.html')
#        return redirect('students:lesson_list')


    

trututoring/classroom/views/classroom.py
from django.shortcuts import redirect, render
from django.views.generic import TemplateView


class SignUpView(TemplateView):
    template_name = 'registration/signup.html'


def home(request):
    if request.user.is_authenticated:
        if request.user.is_teacher:
            return render(request, 'classroom/teachers/values.html')
        else:
            return render(request, 'classroom/students/quiz_list.html')
    return render(request, 'classroom/home.html')

trututoring/classroom/views/students.py
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.db.models import Count
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, ListView, UpdateView, TemplateView

from ..decorators import student_required
from ..forms import StudentTopicsForm, StudentSignUpForm
from ..models import Student, User


class StudentSignUpView(CreateView):
    model = User
    form_class = StudentSignUpForm
    template_name = 'registration/signup_form.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'student'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
#        return render(request, 'classroom/students/quiz_list.html')
        return redirect('students:quiz_list')

@method_decorator([login_required, student_required], name='dispatch')
class StudentTopicsView(UpdateView):
    model = Student
    form_class = StudentTopicsForm
    template_name = 'classroom/students/topics_form.html'
    success_url = reverse_lazy('students:quiz_list')

    def get_object(self):
        return self.request.user.student

    def form_valid(self, form):
        messages.success(self.request, 'topics updated with success!')
        return super().form_valid(form)


@method_decorator([login_required, student_required], name='dispatch')
class QuizListView(TemplateView):
    template_name = 'classroom/students/quiz_list.html'

trututoring/classroom/views/teachers.py
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.db.models import Avg, Count
from django.forms import inlineformset_factory
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import (CreateView, DeleteView, DetailView, ListView,
                                  UpdateView, TemplateView)

from ..decorators import teacher_required
from ..forms import TeacherSignUpForm
from ..models import Subject, Student, User


class TeacherSignUpView(CreateView):
    model = User
    form_class = TeacherSignUpForm
    template_name = 'registration/signup_form.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'tutor'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        #return render(request, 'classroom/teachers/values.html')
        return redirect('teachers:values')


@method_decorator([login_required, teacher_required], name='dispatch')
class TeacherValuesView(TemplateView):
    template_name = 'classroom/teachers/values.html'

classroom/templates/classroom/students/_header.html
<h2>{{user.first_name}}'s Profile</h2>

classroom/templates/classroom/students/availability_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<div class="login-card ">

  <h2 id="title" class="mb-3">Update Your Availability</h2>
  <form method="post" novalidate>
    {% csrf_token %}
    {{ form }}
    <div class="sign-btn">
      <button type="submit" id="yes-btn">Save changes</button>
      <a href="{% url 'students:tutor_list' %}" id="hit-btn">Nevermind</a>
    </div>
  </form>

</div>
{% endblock %}

classroom/templates/classroom/students/grade_level_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<div class="login-card ">

  <h2 id="title" class="mb-3">Update Your Grade Level</h2>
  <form method="post" novalidate>
    {% csrf_token %}
    {{ form }}
    <div class="sign-btn">
      <button type="submit" id="yes-btn">Save changes</button>
      <a href="{% url 'students:tutor_list' %}" id="hit-btn">Nevermind</a>
    </div>
  </form>

</div>
{% endblock %}

classroom/templates/classroom/students/interests_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<div class="login-card ">

  <h2 id="title" class="mb-3">Update Your Subjects</h2>
  <form method="post" novalidate>
    {% csrf_token %}
    {{ form }}
    <div class="sign-btn">
      <button type="submit" id="yes-btn">Save changes</button>
      <a href="{% url 'students:tutor_list' %}" id="hit-btn">Nevermind</a>
    </div>
  </form>

  <script>
    $('option').mousedown(function(e) {
      e.preventDefault();
      var originalScrollTop = $(this).parent().scrollTop();
      console.log(originalScrollTop);
      $(this).prop('selected', $(this).prop('selected') ? false : true);
      var self = this;
      $(this).parent().focus();
      setTimeout(function() {
          $(self).parent().scrollTop(originalScrollTop);
      }, 0);
      
      return false;
    });
  </script>

</div>
{% endblock %}

classroom/templates/classroom/students/lesson_list.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<div class="main-card">
  <div class="row align-items-center my-5">

    <div class="col-lg-5 text-center">
      <h1 class="font-weight-light">Start Learning!</h1>
      <br>
      <p>Below you can explore available tutors in your selected subjects. <br>To get in touch with a tutor, please reach out to the email provided!</p>  
    </div>

    <div class="col-lg-7">
      <div class="card h-100">
        <div class="card-body">
          {% include 'classroom/students/_header.html' with active='new' %}
          <hr id="prof-line"> 
          <p class="text-muted">
            Subjects:&nbsp;{% for subject in user.student.interests.all %} {{ subject.get_html_badge }}{% endfor %}
            <a href="{% url 'students:student_interests' %}"><small>(update)</small></a>
          </p>
          <p class="text-muted">
            School:&nbsp;<span id="badger">{{ user.student.school }}</span>
            <a href="{% url 'students:student_school' %}"><small>(update)</small></a>
          </p>
          <p class="text-muted">
            Grade:&nbsp;{% for grade in user.student.grade_level.all %} {{ grade.get_html_badge }}{% endfor %}
            <a href="{% url 'students:student_grade_level' %}"><small>(update)</small></a>
          </p>
          <p class="text-muted">
            Availability:&nbsp;{% for availability in user.student.availability.all %} {{ availability.get_html_badge }}{% endfor %}
            <a href="{% url 'students:student_availability' %}"><small>(update)</small></a>
          </p>
          <p class="text-muted">
            Sessions/week:&nbsp;{% for session in user.student.sessions.all %} {{ session.get_html_badge }}{% endfor %}
            <a href="{% url 'students:student_sessions' %}"><small>(update)</small></a>
          </p>       
        </div>
      </div>

    </div>
  </div>

  <hr id="prof-line"> 

  <ul class="nav nav-pills mb-3">
    <li id="lesson-tutor" class="nav-item">
      <a class="nav-link" href="{% url 'students:tutor_list' %}">Available Tutors</a>
    </li>
    <li id="lesson-lesson" class="nav-item">
      <a class="nav-link" href="{% url 'students:lesson_list' %}">Your Lessons</a>
    </li>
  </ul>

  <div class="card text-black bg-white my-4 py-2 z-depth-1">
    <div class="card-body">
      <table class="table mb-0 table-striped">
        <thead>
          <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Date</th>
            <th>Zoom Link + Meeting Details</th>
            <th>Lesson Rate</th>
            <th>Paid?</th>
          </tr>
        </thead>
        <tbody>
          
          {% for lesson in lessons %}
            <tr>
              <td class="align-middle">{{ lesson.tutor.user.first_name }} {{ lesson.tutor.user.last_name }}</td>
              <td class="align-middle">
                <a class="material-url" href="mailto:{{lesson.tutor.user.email}}">{{lesson.tutor.user.email}}</a>
              </td>
              <td class="align-middle">{{ lesson.date }}</td>
              <td style="width:40%" class="align-middle">
                <!-- function to generate url link within text -->
                <script>
                  function urlify(text) {
                      var urlRegex = /(((https?:\/\/)|(www\.))[^\s]+)/g;
                      //var urlRegex = /(https?:\/\/[^\s]+)/g;
                      return text.replace(urlRegex, function(url,b,c) {
                          var url2 = (c == 'www.') ?  'http://' +url : url;
                          return '<a class="material-url" href="' +url2+ '" target="_blank">' + url + '</a>';
                      }) 
                  }

                  var text = '{{ lesson.material }}';
                  var html = urlify(text);  

                  document.write(html);
                </script>
              </td>

              <td class="align-middle">
                
                <script>
                  function CurrencyFormatted(amount) {
                    var i = parseFloat(amount);
                    if(isNaN(i)) { i = 0.00; }
                    var minus = '';
                    if(i < 0) { minus = '-'; }
                    i = Math.abs(i);
                    i = parseInt((i + .005) * 100);
                    i = i / 100;
                    s = new String(i);
                    if(s.indexOf('.') < 0) { s += '.00'; }
                    if(s.indexOf('.') == (s.length - 2)) { s += '0'; }
                    s = minus + s;
                    return s;
                  }
                  var amount = '{{ lesson.rate }}';
                  var html = CurrencyFormatted(amount); 
                  document.write('$' + html + '/hour');
                </script>

              </td>

              <td style="font-weight:bold; color:green" class="align-middle">{% if lesson.paid %}Yes{% else %}
                <a id="course-descriptor" href="{% url 'students:process_payment' lesson.pk %}">Pay Now</a>
                {% endif %}
              </td>
            </tr>
          {% empty %}
            <tr>
              <td class="bg-light text-center font-italic" colspan="6">No lessons completed at this time :(</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>

</div>
{% endblock %}

classroom/templates/classroom/students/payment_canceled.html
{% extends 'base.html' %}

{% block content %}
<div class="pay-card ">

    <div class="box-header">
        <h2 id="title">Payment Cancelled</h2>
    </div>
    <div class="hit-btn">
        <a href="{% url 'students:lesson_list' %}" id="hit-btn">Return</a>
    </div>

</div>
{% endblock %}

classroom/templates/classroom/students/payment_done.html
{% extends 'base.html' %}

{% block content %}
<div class="pay-card ">

    <div class="box-header">
        <h2 id="title">Payment Successful!</h2>
    </div>
    <div class="hit-btn">
        <a href="{% url 'students:lesson_list' %}" id="hit-btn">Return</a>
    </div>

</div>
{% endblock %}

classroom/templates/classroom/students/process_payment.html
{% extends 'base.html' %}

{% block content %}
<div class="pay-card">

    <div class="box-header">
        <h2 id="title">Pay with PayPal</h2>
    </div>

    {{ form.render }}
</div>
{% endblock %}

classroom/templates/classroom/students/quiz_list.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<div class="main-card">
  <div class="row align-items-center my-5">

    <div class="col-lg-5 text-center">
      <h1 class="font-weight-light">Start Learning!</h1>
      <br>
      <p>Below you can explore available tutors in your selected subjects. <br>To get in touch with a tutor, please reach out to the email provided!</p>  
    </div>

    <div class="col-lg-7">
      <div class="card h-100">
        <div class="card-body">
          {% include 'classroom/students/_header.html' with active='new' %}
          <hr id="prof-line"> 
          <p class="text-muted">
            Subjects:&nbsp;{% for subject in user.student.interests.all %} {{ subject.get_html_badge }}{% endfor %}
            <a href="{% url 'students:student_interests' %}"><small>(update)</small></a>
          </p>
          <p class="text-muted">
            School:&nbsp;<span class="badge badge-primary" style="background-color:#505050;">{{ user.student.school }}</span>
            <a href="{% url 'students:student_school' %}"><small>(update)</small></a>
          </p>
          <p class="text-muted">
            Grade:&nbsp;{% for grade in user.student.grade_level.all %} {{ grade.get_html_badge }}{% endfor %}
            <a href="{% url 'students:student_grade_level' %}"><small>(update)</small></a>
          </p>
          <p class="text-muted">
            Availability:&nbsp;{% for availability in user.student.availability.all %} {{ availability.get_html_badge }}{% endfor %}
            <a href="{% url 'students:student_availability' %}"><small>(update)</small></a>
          </p>
          <p class="text-muted">
            Sessions/week:&nbsp;{% for session in user.student.sessions.all %} {{ session.get_html_badge }}{% endfor %}
            <a href="{% url 'students:student_sessions' %}"><small>(update)</small></a>
          </p>       
        </div>
      </div>

    </div>
  </div>

  <hr id="prof-line"> 

  <div class="card text-black bg-white my-4 py-2 z-depth-1">
    <div class="card-body">
      <table class="table mb-0 table-striped">
        <thead>
          <tr>
            <th>Name</th>
            <th>Email</th>
            <th>School</th>
            <th>Subjects</th>
            <th>Rate</th>
            <th>TRU Verified</th>
          </tr>
        </thead>
        <tbody>
          <!--
          {% for quiz in quizzes %}
            <tr>
              <td class="align-middle">{{ quiz.owner.user.first_name }} {{ quiz.owner.user.last_name }}</td>
              <td class="align-middle">{{ quiz.name }}</td>
              <td class="align-middle">{{ quiz.subject.get_html_badge }}</td>
              <td class="align-middle"><a id="course-descriptor" href="https://zoom.us/join">{{ quiz.zoom }}</a></td>
            </tr>
          {% endfor %}
          -->
          {% for teacher in teachers %}
            <tr>
              <td class="align-middle">{{ teacher.user.first_name }} {{ teacher.user.last_name }}</td>
              <td class="align-middle">{{ teacher.user.email }}</td>
              <td class="align-middle">{{ teacher.school }}</td>
              <td class="align-middle">{% for subject in teacher.interests.all %} {{ subject.get_html_badge }}{% endfor %}</td>
              {% if teacher.verified %}
                <td class="align-middle">$22.50/hour</a></td>
              {% else %}
                <td class="align-middle">${{ teacher.rate }}/hour</a></td>
              {% endif %}
              <td class="align-middle">{% if teacher.verified %}Yes{% else %}No{% endif %}</td>
            </tr>
          {% empty %}
            <tr>
              <td class="bg-light text-center font-italic" colspan="6">No tutors matching your preferences at the moment :(</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>

</div>
{% endblock %}

classroom/templates/classroom/students/school_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<div class="login-card ">

  <h2 id="title" class="mb-3">Update Your School</h2>
  <form method="post" novalidate>
    {% csrf_token %}
    {{ form }}
    <div class="sign-btn">
      <button type="submit" id="yes-btn">Save changes</button>
      <a href="{% url 'students:tutor_list' %}" id="hit-btn">Nevermind</a>
    </div>
  </form>

</div>
{% endblock %}

classroom/templates/classroom/students/sessions_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<div class="login-card ">

  <h2 id="title" class="mb-3">Update Sessions Per Week</h2>
  <form method="post" novalidate>
    {% csrf_token %}
    {{ form }}
    <div class="sign-btn">
      <button type="submit" id="yes-btn">Save changes</button>
      <a href="{% url 'students:tutor_list' %}" id="hit-btn">Nevermind</a>
    </div>
  </form>

</div>
{% endblock %}